### ISSUE TITLE
Omega Station: Conflicting Atmospherics in Cargo

### ISSUE THREAD

**Issue by Chaos-Neo** [TheCanoePirates/TCPStation#40]
## Round ID:
[105](https://scrubby.melonmesa.com/round/105)

## Reproduction:

Loading in the current version of Omega Station and heading up to the cargo shuttle area as shown in both images will always spawn atmospheric pipes as seen in image 1. This causes there to be a 'feedback loop' where both the air supply and air disposal pipes are connected to the same loop without any separation causing issues with the atmospheric system and possibly server latency.

## Images:
**Image 1: Problem area and condition (pipes are unsecured but not changed)**
![image](https://user-images.githubusercontent.com/72242477/94888852-f7b1af80-043f-11eb-8d7e-1f56312e46a5.png)

**Image 2: Personal air disposal setup requiring only changes with disposal pipes**
![image](https://user-images.githubusercontent.com/72242477/94888961-55de9280-0440-11eb-9f3d-3086ee585423.png)

**Comment by Coolguy3289** [comment]
Also relates to #30
