### ISSUE TITLE
TComms Atmos does not recover

### ISSUE THREAD

**Issue by Coolguy3289** [TheCanoePirates/TCPStation#46]
## Reproduction: Open doors into tcomms cold room, then close them. The temp does not recover, nor does the lost oxygen.

**Comment by Kei-Shin** [comment]
Tbf It's not exactly meant to recover oxygen all it cares about is that the room is cold. Most maps don't even include the freezer I could just remove it. If players want to set up a system for it they can do so as needed.

**Comment by Coolguy3289** [comment]
There's no buffer zone between the cold area and control room, which is why this becomes such an issue imo
